### ISSUE TITLE
移动端高清适配方案

### ISSUE THREAD

**Issue by Chersquwn** [Chersquwn/Chersquwn.github.io#4]
由于现在手机的屏幕尺寸、分辨率不一，移动端页面要想很好地还原设计稿，就需要做好适配，说到底就是希望一份代码能够在不同尺寸、分辨率的机子上跑出相同的效果，这当中会遇到2个问题：
1. 高清屏幕的适配；
2. 1px border的实现

网上有很多的方案，总结来说有以下几种：
1、响应式布局
2、流式布局、弹性盒布局
3、使用rem布局
4、简单粗暴px布局

## 响应式布局
这里的响应式布局不是指移动端到PC的响应式布局，或者应该说是使用media根据不同的屏幕尺寸进行分断点微调
```css
@media (min-width: 320px) {
  .container {
    width: 200px;
  }
}
@media (min-width: 375px) {
  .container {
    width: 240px;
  }
}
```
缺点：设计稿还原度不够高，根据不同尺寸进行微调工作量大

## 流式布局
高度固定，宽度使用百分比、vw或者flex进行布局，viewport设置为
```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```
缺点：设计稿还原度不够高

## rem布局
使用rem布局有两种方式，一种是不对viewport进行缩放，另一种是对viewport进行缩放
### 不对viewport缩放
将viewport设置为
```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```
既然是使用rem布局，那就是需要根据屏幕的尺寸对html的font-size进行调整，假设设计稿的宽度是750px，那么
```javascript
document.documentElement.style.fontSize = document.documentElement.clientWidth / (750 / 100) + 'px';
```
元素的大小这么写
```css
.container {
  width: 3rem;    //750px设计稿下的300px
}
```
缺点：1px border需要另外处理

### 对viewport进行缩放
这种方式淘宝提供了[lib-flexible](https://github.com/amfe/lib-flexible)的库进行处理，具体可以看[使用Flexible实现手淘H5页面的终端适配](https://github.com/amfe/article/issues/17)

## 简单粗暴px布局
根据设计稿宽度，假设设计稿宽度为750px，将viewport设置为
```html
<meta name="viewport" content="width=750, user-scalable=no">
```
然后元素的大小跟设计稿上的大小一样，浏览器会根据手机的屏幕宽度对页面自动缩放，不需要人为去计算
缺点：由于没有显示设置scale的值，某些浏览器比如UC会出问题，需要手动计算一下缩放添加到viewport上
